#
# docker-compose file pour le déploiement initial de l'application geoquizz2
# Documentation complète : https://bitbucket.org/canals5/docker-things
#
# ajouter les vhosts des services web dans le fichier /etc/vhosts
# de la machine hôte :
# exemple pour le service api.public :
# 127.0.0.1   api.lbs.local
# pour accéder à ce service : https://api.lbs.local:10443
#                      ou   :  http://api.lbs.local:10080
# accès au service adminer : http://localhost:8080
# accès au service mysql depuis le container api.public : utiliser le hostname "db"

version: "2"
networks:
  learn_network:
    driver: bridge

services:
  api.public:
    image: canals/php
    container_name: api.learn.local.local
    environment:
        - VHOST_HOSTNAME=api.learn.local
        - VHOST_DOCROOT=/var/www/api
#       - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
#       - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
    ports:
        - "10080:80"
        - "10443:443"
    volumes :
        - ./api:/var/www/api
        - ./src:/var/www/src
        - ./vendor:/var/www/vendor
        - ./uploads:/var/www/uploads
    networks:
        - learn_network
    links :
        - mysql:learn

#############################
# mysql + adminer / can be replaced by mariadb
#############################
  mysql:
    image: mariadb:latest
    container_name: db.learn.local
    environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=admin
          - MYSQL_DATABASE=learn
    ports:
          - "3603:3306"
    networks:
          - learn_network
    volumes :
          - ./data:/var/data

  adminer:
     image: adminer
     container_name: admin.learn
     ports:
          - "8082:8080"
     networks:
          - learn_network
     links:
          - mysql:learn

######################
############ Migration Service
######################
  db.migrate:
      image: canals/php
      container_name: migrate.learn.local
      environment:
          - VHOST_HOSTNAME=migrate.learn.local
          - VHOST_DOCROOT=/var/www/data
  #      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
  #       - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
      ports:
          - "10083:80"
          - "10444:443"
      volumes :
          - ./src/config:/var/www/data
          - ./src:/var/www/src
          - ./vendor:/var/www/vendor
      networks:
          - learn_network
      links :
          - mysql:learn


######################
############ Chat service
######################
  api.chat:
      image: canals/php
      container_name: chat.learn.local
      environment:
          - VHOST_HOSTNAME=chat.learn.local
          - VHOST_DOCROOT=/var/www/chat
  #       - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
  #       - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128/
      ports:
          - "10084:80"
          - "10445:443"
      volumes :
          - ./chat:/var/www/chat
          - ./src:/var/www/src
          - ./vendor:/var/www/vendor
      networks:
          - learn_network
      links :
          - mysql:learn

